---
image:
  repository: n8nio/n8n
  pullPolicy: Always
  tag: latest

main:
  config:
    n8n:
      hide_usage_page: false
    db:
      type: postgresdb
      postgresdb:
        host: n8n-postgresql-0.n8n-postgresql-hl.n8n-devel.svc.cluster.local
        user: n8n
    queue:
      health:
        check:
          active: true
      bull:
        redis:
          host: redis.n8n-devel.svc.cluster.local
          port: 6379
  secret:
    n8n:
      encryption_key: "lqn3allBu5x=xFG.GPBnU5LArv3ZSY6E"
  extraEnv:
    WEBHOOK_URL:
      value: 'https://n8n-devel.app.bitbull.ch'
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: n8n-postgresql
          key: password
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
  service:
    type: NodePort
    port: 5678
  persistence:
    enabled: true
    type: dynamic
    accessModes:
      - ReadWriteOnce
    size: 1Gi

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: n8n-devel.app.bitbull.ch
      paths:
        - /
  tls:
    - hosts:
        - n8n-devel.app.bitbull.ch
