---
ingress:
  enabled: true
  className: traefik
  hosts:
    - host: n8n-devel.app.bitbull.ch
      paths:
        - /
  tls:
    - hosts:
        - n8n-devel.app.bitbull.ch

main:
  config:
    n8n:
      hide_usage_page: false
  secret:
    n8n:
      encryption_key: "lqn3allBu5x=xFG.GPBnU5LArv3ZSY6E"
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
  service:
    type: NodePort
    port: 5678

  persistence:
    enabled: true
    type: dynamic
    accessModes:
      - ReadWriteOnce
    size: 1Gi

